name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U openai-whisper
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name whisper_auto2lrc main.py

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/whisper_auto2lrc.exe
          asset_name: whisper_auto2lrc.exe
          asset_content_type: application/octet-stream
